name: NeuronalNetworkCariad
channels:
  - defaults
dependencies:
  - python=3.12.4
  - _tflow_select=2.2.0
  - abseil-cpp=20211102.0
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - category_encoders=2.6.1
  - certifi=2024.2.2
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - fonttools=4.25.0
  - freetype=2.12.1
  - gast=0.4.0
  - h5py=3.9.0
  - hdf5=1.12.1
  - icc_rt=2022.1.0
  - ipykernel=6.28.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl
  - libdeflate=1.17
  - libffi=3.4.4
  - libiconv=1.16
  - libpng=1.6.39
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - nbclassic
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.5.6
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nltk=3.8.1
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - openjpeg=2.3.0
  - overrides=7.4.0
  - packaging=23.1
  - pandas=2.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=3.10.0
  - plotly=5.9.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - referencing=0.30.2
  - regex=2023.10.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - scikit-learn=1.3.0
  - scipy=1.11.3
  - send2trash=1.8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sleef=3.5.1
  - sniffio=1.2.0
  - soupsieve=2.5
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - tenacity=8.2.2
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - tzdata=2023c
  - ucrt=10.0.20348.0
  - vc=14.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.35.1
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - braceexpand==0.1.7
      - chardet==4.0.0
      - faiss-cpu
      - filelock==3.13.1
      - fpdf==1.7.2
      - fsspec==2024.2.0
      - grpcio==1.65.1
      - idna==2.10
      - imageio==2.34.0
      - intel-openmp==2021.4.0
      - lorem==0.1.1
      - markdown==3.6
      - mkl==2021.4.0
      - mpmath==1.2.1
      - networkx==3.2.1
      - numpy==1.26.4
      - onnx
      - onnxscript==0.1.0.dev20240315
      - opencv-python==4.9.0.80
      - pathlib2==2.3.7.post1
      - protobuf==4.25.3
      - pthflops==0.4.2
      - reportlab==4.2.0
      - requests==2.25.1
      - seaborn==0.13.2
      - sympy==1.12
      - tabulate==0.9.0
      - tbb==2021.11.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - typing-extensions==4.8.0
      - urllib3==1.26.18
      - webdataset==0.2.86
      - werkzeug==3.0.3
